#!/bin/bash

read -p "username: " username
read -p "ride_id: " ride_id

curl -i -H "Content-Type: application/json" -X DELETE -b cookie-jar -k 'https://info3103.cs.unb.ca:40765/users/'$username'/ridesoffered/'$ride_id