#!/bin/bash

read -p "username: " username
read -p "ride_id: " ride_id
read -p "driver_id: " driver_id

curl -i -H "Content-Type: application/json" -X POST -d '{"ride_id": "'$ride_id'", "driver_id": "'$driver_id'"}' -k 'https://info3103.cs.unb.ca:40765/users/'$username'/ridestaken'