#!/bin/bash

read -p "username: " username
read -p "ride_id: " ride_id
read -p "departure_time: " departure_time

curl -i -H "Content-Type: application/json" -X PUT -d '{"departure_time": "'$departure_time'"}' -k 'https://info3103.cs.unb.ca:40765/users/'$username'/ridesoffered/'$ride_id